version: '3.8'

services:
  frontend:
    build:
      context: ./ticket-booking-system
      dockerfile: Dockerfile
    ports:
      - "4200:80"  # Map Nginx port to local port
    networks:
      - app-network

  backend:
    build:
      context: ./ticket-backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    environment:
      - MONGO_URI=mongodb://db:27017/mydatabase
      - NODE_ENV=production
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mongo:6
    container_name: mongodb
    ports:
      - "27017:27017"
    networks:
      - app-network
    volumes:
      - mongodb_data:/data/db

networks:
  app-network:

volumes:
  mongodb_data:
